---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

language: zh-CN
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
