version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '{{ports.redis.ip}}:{{ports.redis.port}}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass {{variables.password.value}}
    volumes: 
      - ./data:/data
